Repository microsoft/recommenders, pull requests merged in 2019-02, with the labels that each got.

#476 Deeprec/second
  notebooks/00_quick_start/README.md
Labels: milestone

#482 added papermill documentation
  TESTS.md
  tests/conftest.py
Labels: documentation, test

#487 Readme / Comparison Updates
  README.md
  notebooks/03_evaluate/comparison.ipynb
Labels: documentation

#520 Added note to readme and ALS notebook when a pyspark environment is necessary
  README.md
  notebooks/00_quick_start/als_movielens.ipynb
  notebooks/02_model/als_deep_dive.ipynb
Labels: documentation, style improvement
